package gui.consultas;

import dao.ProdutoDAO;
import gui.Navegacao;
import gui.cadastros.CadastroProduto;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import modelo.Produto;

public class ConsultaProdutos extends javax.swing.JFrame {

    public ConsultaProdutos() {
        initComponents();

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowActivated(java.awt.event.WindowEvent evt) {
                LoadProdutos();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fieldBusca = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        comboTipo = new javax.swing.JComboBox<>();
        btnVoltar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Produtos Cadastrados");

        jLabel9.setText("Filtro de busca: ");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Cadastrar Produto");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.setToolTipText("Selecione na tabela o produto a ser atualizado e aperte o botão");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Descrição", "Procedencia", "Estoque"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaProdutos.setColumnSelectionAllowed(true);
        tabelaProdutos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelaProdutos);
        tabelaProdutos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tabelaProdutos.getColumnModel().getColumnCount() > 0) {
            tabelaProdutos.getColumnModel().getColumn(0).setResizable(false);
            tabelaProdutos.getColumnModel().getColumn(1).setResizable(false);
            tabelaProdutos.getColumnModel().getColumn(2).setResizable(false);
            tabelaProdutos.getColumnModel().getColumn(3).setResizable(false);
            tabelaProdutos.getColumnModel().getColumn(4).setResizable(false);
        }

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Código", "Nome" }));
        comboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jButton1.setText("Export para CSV");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fieldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar)
                                .addGap(365, 365, 365)
                                .addComponent(btnAtualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnExcluir))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(31, 31, 31)
                                .addComponent(btnCadastrar)))
                        .addGap(60, 60, 60))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 925, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(30, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltar)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnCadastrar)
                    .addComponent(jButton1))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(fieldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnExcluir)
                    .addComponent(btnAtualizar)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnVoltar)
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void LoadProdutos() {
        try {
            ProdutoDAO dao = new ProdutoDAO();
            List<Produto> produtos = dao.listar();

            DefaultTableModel DFT = (DefaultTableModel) tabelaProdutos.getModel();
            DFT.setRowCount(0);

            for (Produto produto : produtos) {
                DFT.addRow(new Object[]{produto.getIdProduto(), produto.getNome(), produto.getDescricao(), produto.getProcedencia(), produto.getQuantidade()});
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar database: \n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int tipoSel = comboTipo.getSelectedIndex();
        
        String busca = fieldBusca.getText();
        if (fieldBusca.getText().isBlank()) {
                JOptionPane.showMessageDialog(null, "O campo não pode ser vazio");
                LoadProdutos();
                return;
            }
        
        if (tipoSel == 1) {
            ProdutoDAO dao = new ProdutoDAO();
            Produto produto = dao.consultarID(Integer.parseInt(busca));
            
            try {
                DefaultTableModel DFT = (DefaultTableModel) tabelaProdutos.getModel();
                DFT.setRowCount(0);

                DFT.addRow(new Object[]{produto.getIdProduto(), produto.getNome(), produto.getDescricao(), produto.getProcedencia(), produto.getQuantidade()});
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao buscar produto \n", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            
        } else if (tipoSel == 2) {
            ProdutoDAO dao = new ProdutoDAO();
            Produto produto = dao.consultarNome(busca);
            
            try {
                DefaultTableModel DFT = (DefaultTableModel) tabelaProdutos.getModel();
                DFT.setRowCount(0);

                DFT.addRow(new Object[]{produto.getIdProduto(), produto.getNome(), produto.getDescricao(), produto.getProcedencia(), produto.getQuantidade()});
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao buscar produto \n", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um filtro! \n", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        CadastroProduto tela = new CadastroProduto();
        tela.setVisible(true);
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        int row = tabelaProdutos.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Você deve selecionar um produto da tabela!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String idTable = tabelaProdutos.getModel().getValueAt(row, 0).toString();

        ProdutoDAO dao = new ProdutoDAO();
        Produto produto = dao.consultarID(Integer.parseInt(idTable));

        CadastroProduto tela = new CadastroProduto(produto);
        tela.setVisible(true);
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int row = tabelaProdutos.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Você deve selecionar um produto da tabela!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String id = tabelaProdutos.getModel().getValueAt(row, 0).toString();

        ProdutoDAO dao = new ProdutoDAO();
        Produto produto = dao.consultarID(Integer.parseInt(id));

        int valor = JOptionPane.showConfirmDialog(null, "Deseja apagar esse produto? \nNome: " + produto.getNome(), "Confirmar", JOptionPane.YES_NO_OPTION);
        if (valor == 0) {
            try {
                dao.remover(produto);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao remover produto \n", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void comboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        Navegacao n = new Navegacao();
        n.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                 try {
            TableModel model = tabelaProdutos.getModel();
            // Define o caminho completo para o arquivo CSV.
            // Você pode tornar isso configurável ou usar um JFileChooser para o usuário escolher.
            File outputFile = new File();//tem que setar ainda
            FileWriter csvWriter = new FileWriter(outputFile);

            // 1. Define os nomes das colunas que você deseja exportar.
            List<String> desiredColumnNames = Arrays.asList("Nome", "Procedencia", "Estoque");

            // 2. Encontra os índices reais dessas colunas no modelo da JTable.
            // Isso garante que você pegue a coluna correta, independentemente da ordem.
            List<Integer> desiredColumnIndices = new ArrayList<>();
            for (String desiredName : desiredColumnNames) {
                boolean found = false;
                for (int col = 0; col < model.getColumnCount(); col++) {
                    if (model.getColumnName(col).equals(desiredName)) {
                        desiredColumnIndices.add(col);
                        found = true;
                        break; // Coluna encontrada, passa para o próximo nome desejado.
                    }
                }
                if (!found) {
                    // Exibe um aviso se uma coluna desejada não for encontrada na tabela.
                    System.err.println("Aviso: Coluna '" + desiredName + "' não encontrada na tabela.");
                    // Você pode optar por pular essa coluna ou exibir um erro fatal aqui.
                }
            }

            // Verifica se alguma coluna foi encontrada antes de prosseguir
            if (desiredColumnIndices.isEmpty()) {
                JOptionPane.showMessageDialog(null,
                    "Nenhuma das colunas especificadas ('Nome', 'Procedencia', 'Estoque') foi encontrada na tabela.",
                    "Erro de Exportação", JOptionPane.WARNING_MESSAGE);
                csvWriter.close();
                return;
            }

            // 3. Escreve a linha do cabeçalho (nomes das colunas) no CSV.
            for (int i = 0; i < desiredColumnNames.size(); i++) {
                csvWriter.append(escapeCsvValue(desiredColumnNames.get(i))); // Escapa o nome da coluna
                if (i < desiredColumnNames.size() - 1) {
                    csvWriter.append(",");
                }
            }
            csvWriter.append("\n"); // Nova linha após os cabeçalhos

            // 4. Escreve as linhas de dados no CSV.
            for (int row = 0; row < model.getRowCount(); row++) { // Itera por todas as linhas da tabela
                for (int colIndex = 0; colIndex < desiredColumnIndices.size(); colIndex++) { // Itera pelas colunas desejadas
                    int actualColumnModelIndex = desiredColumnIndices.get(colIndex);
                    Object value = model.getValueAt(row, actualColumnModelIndex);

                    // Converte o valor para String e aplica o escape de CSV.
                    String cellValue = (value == null) ? "" : value.toString();
                    csvWriter.append(escapeCsvValue(cellValue));

                    if (colIndex < desiredColumnIndices.size() - 1) {
                        csvWriter.append(",");
                    }
                }
                csvWriter.append("\n"); // Nova linha após cada linha de dados
            }

            csvWriter.flush(); // Garante que todos os dados sejam escritos no arquivo
            csvWriter.close(); // Fecha o FileWriter

            JOptionPane.showMessageDialog(null,
                "Dados exportados com sucesso para:\n" + outputFile.getAbsolutePath(),
                "Exportação Concluída", JOptionPane.INFORMATION_MESSAGE);

        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,
                "Erro ao exportar dados para CSV.\nVerifique se o arquivo não está em uso ou se você tem permissão de escrita.\nDetalhes: " + e.getMessage(),
                "Erro de Exportação", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,
                "Ocorreu um erro inesperado durante a exportação: " + e.getMessage(),
                "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private static String escapeCsvValue(String value) {
        if (value == null) {
            return "";
        }
        // Se o valor contiver vírgulas, aspas duplas ou quebras de linha, ele deve ser envolvido em aspas.
        // Além disso, todas as aspas duplas dentro do valor devem ser dobradas.
        if (value.contains(",") || value.contains("\n") || value.contains("\"")) {
            return "\"" + value.replace("\"", "\"\"") + "\"";
        }
        // Se o valor não contiver caracteres especiais, retorne-o como está.
        return value;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JTextField fieldBusca;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaProdutos;
    // End of variables declaration//GEN-END:variables
}
