package gui.cadastros;

import dao.ProdutoDAO;
import gui.consultas.ConsultaProdutos;
import javax.swing.JOptionPane;
import modelo.Produto;

public class CadastroProduto extends javax.swing.JFrame {

    private boolean editMode = false;
    private Produto produtoEditando = null;

    // padrão: cadastrar
    public CadastroProduto() {
        initComponents();
        editMode = false;
    }

    // editar
    public CadastroProduto(Produto produto, ConsultaProdutos consultaProdutos) {
        initComponents();
        editMode = true;
        produtoEditando = produto;

        jLabel1.setText("Alterar Produto");
        fieldNome.setText(produto.getNome());
        fieldDescricao.setText(produto.getDescricao());
        fieldProcedencia.setText(produto.getProcedencia());
        panelRegistro.remove(labelQtde);
        panelRegistro.remove(fieldQtde);
        btnRegistrar.setText("Atualizar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panelRegistro = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        fieldProcedencia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fieldDescricao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        labelQtde = new javax.swing.JLabel();
        fieldQtde = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        fieldNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Registrar Produto");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        fieldProcedencia.setMinimumSize(new java.awt.Dimension(286, 25));

        jLabel6.setText("Procedência:");

        fieldDescricao.setMinimumSize(new java.awt.Dimension(286, 25));

        jLabel4.setText("Descrição:");

        labelQtde.setText("Quantidade Inicial:");

        fieldQtde.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        fieldQtde.setMinimumSize(new java.awt.Dimension(286, 25));

        jLabel2.setText("Nome:");

        fieldNome.setMinimumSize(new java.awt.Dimension(286, 25));

        javax.swing.GroupLayout panelRegistroLayout = new javax.swing.GroupLayout(panelRegistro);
        panelRegistro.setLayout(panelRegistroLayout);
        panelRegistroLayout.setHorizontalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(labelQtde)
                    .addComponent(jLabel6)
                    .addComponent(fieldQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(fieldProcedencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fieldDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fieldNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistroLayout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .addComponent(btnLimpar)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrar)
                .addGap(22, 22, 22))
        );
        panelRegistroLayout.setVerticalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldProcedencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelQtde)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar)
                    .addComponent(btnRegistrar))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(panelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(panelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try {
            //validacao
            if (editMode) {
                if ((fieldNome.getText().isEmpty()) || (fieldDescricao.getText().isEmpty())
                        || (fieldProcedencia.getText().isEmpty())) {
                    JOptionPane.showMessageDialog(null, "os campos não podem ser vazios");
                    return;
                }

                Produto produto = new Produto();
                produto.setNome(fieldNome.getText());
                produto.setDescricao(fieldDescricao.getText());
                produto.setProcedencia(fieldProcedencia.getText());

                ProdutoDAO dao = new ProdutoDAO();

                produto.setIdProduto(produtoEditando.getIdProduto());
                dao.atualizar(produto);
                JOptionPane.showMessageDialog(null, "Produto atualizado com sucesso");
                
            } else {
                if ((fieldNome.getText().isEmpty()) || (fieldDescricao.getText().isEmpty())
                 || (fieldProcedencia.getText().isEmpty()) || (fieldQtde.getText().isEmpty())) {
                    JOptionPane.showMessageDialog(null, "Os campos não podem ser vazios");
                    return;
                }

                Produto produto = new Produto();
                produto.setNome(fieldNome.getText());
                produto.setDescricao(fieldDescricao.getText());
                produto.setProcedencia(fieldProcedencia.getText());

                ProdutoDAO dao = new ProdutoDAO();
                
                dao.inserir(produto);
                JOptionPane.showMessageDialog(null, "Produto cadastrado com sucesso");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro em inserir na base de dados: \n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        fieldNome.setText("");
        fieldDescricao.setText("");
        fieldProcedencia.setText("");
        fieldQtde.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JTextField fieldDescricao;
    private javax.swing.JTextField fieldNome;
    private javax.swing.JTextField fieldProcedencia;
    private javax.swing.JFormattedTextField fieldQtde;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelQtde;
    private javax.swing.JPanel panelRegistro;
    // End of variables declaration//GEN-END:variables
}
